Make the style of AEP-135: Delete consistent.
aep-dev/aep.dev pull request #124
Opened 2024-03-14 02:46 UTC by rofrankel

* Proto tabs before OAS tabs.
* Generic HTTP guidance factored out of IDL-specific tabs.
* RPC section separated from request section.

2024-03-14 15:47 UTC, mkistler requested changes
A few small problems and need more consistency in the guidance section.

2024-04-12 19:18 UTC, rofrankel commented on aep/general/0135/aep.md.j2
> +````proto
Nope! Fixed.

2024-04-12 19:18 UTC, rofrankel commented on aep/general/0135/aep.md.j2
> +````
Agreed, fixed.

2024-04-12 19:36 UTC, rofrankel commented on aep/general/0135/aep.md.j2
> +- The method's name **must** begin with the word `Delete`. The remainder of the
I actually think all of these bullet points are applicable to both protobuf and OAS APIs, so I've moved them out (and slightly generalized the phrasing).

We've been using "method" everywhere to refer to both gRPC RPCs and OAS operations, so I stuck to that convention here.

2024-04-12 19:37 UTC, rofrankel commented on aep/general/0135/aep.md.j2
>  - The response message **should** be `google.protobuf.Empty`.
Done.

2024-04-12 19:51 UTC, rofrankel commented
I caught my IDE adding the four backticks, I think because there was an unclosed sequence (and maybe it thought a normal three-backtick code block was supposed to be inside another code block or something)?  Anyway, that's fixed now, and I made some other adjustments too.  I think all the comments should be addressed.

2024-04-14 15:34 UTC, mkistler approved these changes
Looks good! 👍

2024-04-14 19:17 UTC, merged